services:
  - type: web
    name: eduvisor-backend
    env: node
    plan: free
    rootDir: advisor-backend
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: static
    name: eduvisor-frontend
    rootDir: advisor-frontend
    buildCommand: npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
